In [117]:
import numpy as np
import pandas as pd

In [118]:
train_df= pd.read_csv('muzee.csv')

In [119]:
# Subtask 1
answer1= pd.DataFrame([{
    "id": 1,
    "subtaskID": 1,
    "answer": len(train_df)
}])

answer1.head()

   id  subtaskID  answer
0   1          1    1008

In [120]:
# Subtask 2
answer2= pd.DataFrame([{
    "id": 2,
    "subtaskID": 2,
    "answer": len(train_df[train_df['județul'] == 'București'])
}])

answer2.head()

   id  subtaskID  answer
0   2          2      59

In [121]:
# Subtask 3
answer3= pd.DataFrame([{
    "id": 3,
    "subtaskID": 3,
    "answer": np.sum(train_df.isna().sum().values != 0)
}])

answer3.head()

   id  subtaskID  answer
0   3          3      33

In [122]:
# Subtask 4
answer4= pd.DataFrame([{
    "id": 4,
    "subtaskID": 4,
    "answer": train_df['anul înființării'].value_counts().index[0]
}])

answer4.head()

   id  subtaskID answer
0   4          4   2006

In [123]:
# Subtask 5
answer5= pd.DataFrame([{
    "id": index,
    "subtaskID": 5,
    "answer": train_df['județul'].value_counts().loc[index]
} for index in train_df['județul'].value_counts().index])

answer5.head()

          id  subtaskID  answer
0       Alba          5      60
1  București          5      59
2      Sibiu          5      47
3      Neamț          5      43
4    Prahova          5      41

In [124]:
# Subtask 6
answer6= pd.DataFrame([{
    "id": train_df.iloc[idx]["_id"],
    "subtaskID": 6,
    "answer": round(train_df.iloc[idx].notna().sum()/ len(train_df.columns)* 100, 2)
} for idx in train_df.index])

answer6.head()

   id  subtaskID  answer
0   1          6   81.82
1   2          6   81.82
2   3          6   77.27
3   4          6   79.55
4   5          6   65.91

In [125]:
# Subtask 7
answer7= pd.DataFrame([{
    "id": 7,
    "subtaskID": 7,
    "answer": round(answer6['answer'].sum()/len(train_df), 2)
} ])

answer7.head()

   id  subtaskID  answer
0   7          7   72.59

In [126]:
# Subtask 8
answer8= pd.DataFrame([{
    "id": 8,
    "subtaskID": 8,
    "answer": round(len(answer6[answer6['answer'] == answer6['answer'].max()])/ len(answer6) * 100, 2)
} ])

answer8.head()

   id  subtaskID  answer
0   8          8    1.49

In [127]:
answer= pd.concat([answer1, answer2, answer3, answer4, answer5, answer6, answer7, answer8])
answer.to_csv("submission.csv", index= False)